on:
  push:
jobs:
  linux-amd64:
    if: false
    runs-on: ubuntu-20.04
    container:
      image: amd64/centos:7.9.2009
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: |
        set -e -x
        curl -Lo cmake-3.23.2-linux-x86_64.tar.gz 'https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.tar.gz'
        echo "aaced6f745b86ce853661a595bdac6c5314a60f8181b6912a0a4920acfa32708  cmake-3.23.2-linux-x86_64.tar.gz" | sha256sum -c
        tar -xf cmake-3.23.2-linux-x86_64.tar.gz
        mv cmake-3.23.2-linux-x86_64 cmake
        yum -y install libX11-devel mesa-libGL-devel java-11-openjdk-devel "@Development Tools"
    - name: build linux-amd64
      run: |
        set -e -x
        mkdir -p build/linux-amd64
        cd build/linux-amd64
        ../../cmake/bin/cmake ../../
        ../../cmake/bin/cmake --build . --config Release
    - uses: actions/upload-artifact@v3
      with:
        name: linux-amd64
        path: build/linux-amd64/librlawt.so
        retention-days: 1
        if-no-files-found: error
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      shell: bash
      run: |
        set -e -x
        curl -Lo jdk-11.0.15+10.zip 'https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.15%2B10/OpenJDK11U-jdk_x86-32_windows_hotspot_11.0.15_10.zip'
        echo "c8aa33913b27bb09cc66342e567b3a1fe0f4b136569e57e713bd56ef540d4105  jdk-11.0.15+10.zip" | sha256sum -c
        unzip jdk-11.0.15+10.zip
    - name: build windows-x86
      shell: bash
      run: |
        set -e -x
        mkdir -p build/windows-x86
        cd build/windows-x86
        # cmake isn't smart enough to find jawt of the correct arch
        cmake ../../ -A Win32 -DJAVA_JVM_LIBRARY=../../jdk-11.0.15+10/lib/jvm.lib  -DJAVA_AWT_LIBRARY=../../jdk-11.0.15+10/lib/jawt.lib
        cmake --build . --config Release
    - name: build windows-amd64
      shell: bash
      run: |
        set -e -x
        mkdir -p build/windows-amd64
        cd build/windows-amd64
        cmake ../../
        cmake --build . --config Release
    - uses: actions/upload-artifact@v3
      with:
        name: windows-x86
        path: build/windows-x86/Release/rlawt.dll
        retention-days: 1
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: windows-amd64
        path: build/windows-amd64/Release/rlawt.dll
        retention-days: 1
        if-no-files-found: error

